### ISSUE TITLE
KeyError: 'u_feedLifeCycle' 报错

### ISSUE THREAD

**Issue by Kissingbymodi** [timberding/CTR-prediction-through-cross-domain-data-from-ads-and-news-feeds#1]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 341, in <module>
    train_predict(input_dir, output_dir, model_config_path)
  File "train.py", line 318, in train_predict
    train_data, test_data, feature_columns = get_input_data(train_df, test_df, config)
  File "train.py", line 96, in get_input_data
    all_data_df[feature].fillna(-1, inplace=True)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'u_feedLifeCycle'

运行 python train.py 报错

**Comment by wangqiangJN** [comment]
你好请问这个怎么解决，谢谢
